creation_rules:
  - path_regex: .*secrets?.yaml
    encrypted_regex: ^(data|stringData)$
    azure_keyvault: https://k8s-training.vault.azure.net/keys/Dev-Sops/3806b6b5836f46dc96a57523c1a583e0
    age: age1zqf9z96wav0x4lxcl8wsdk6zpph2m2qk247tu2kwmrfstx64dfyq8wh0yr
  - path_regex: .*secretvalue.yaml
    azure_keyvault: https://k8s-training.vault.azure.net/keys/Dev-Sops/3806b6b5836f46dc96a57523c1a583e0
    age: age1zqf9z96wav0x4lxcl8wsdk6zpph2m2qk247tu2kwmrfstx64dfyq8wh0yr
  - path_regex: .*.env
    azure_keyvault: https://k8s-training.vault.azure.net/keys/Dev-Sops/3806b6b5836f46dc96a57523c1a583e0
    age: age1zqf9z96wav0x4lxcl8wsdk6zpph2m2qk247tu2kwmrfstx64dfyq8wh0yr
