creation_rules:
  - path_regex: .*secrets?.yaml
    encrypted_regex: ^(data|stringData)$
    azure_keyvault: https://k8s-training.vault.azure.net/keys/Dev-Sops/3806b6b5836f46dc96a57523c1a583e0
    age: age19kyyjnd32na99sn2d4ktqddykrmnghu6tk34fsy9l9duyu2g95ssypk7vy
  - path_regex: .*secretvalue.yaml
    azure_keyvault: https://k8s-training.vault.azure.net/keys/Dev-Sops/3806b6b5836f46dc96a57523c1a583e0
    age: age19kyyjnd32na99sn2d4ktqddykrmnghu6tk34fsy9l9duyu2g95ssypk7vy
  - path_regex: .*.env
    azure_keyvault: https://k8s-training.vault.azure.net/keys/Dev-Sops/3806b6b5836f46dc96a57523c1a583e0
    age: age19kyyjnd32na99sn2d4ktqddykrmnghu6tk34fsy9l9duyu2g95ssypk7vy
