apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: ingress-nginx

resources:
  - ../../base/ingress-nginx
  - tls-secret.yaml

patches:
- path: nginx-ingress-release-patch.yaml