---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: nginx-ingress
spec:
  chart:
    spec:
      version: 4.13.3
  values:
    controller:
      extraArgs:
        default-ssl-certificate: "nginx-ingress/tls-secret"