---
apiVersion: kustomize.toolkit.fluxcd.io/v1beta2
kind: Kustomization
metadata:
  name: infrastructure
  namespace: flux-system
spec:
  decryption:
    provider: sops
    secretRef:
      name: age-key-secret
  interval: 1m0s
  path: ./fluxcd/infrastructure/local
  prune: true
  sourceRef:
    kind: GitRepository
    name: flux-system
