apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
- deployment.yaml
- ingress.yaml
- service.yaml
- namespace.yaml

configMapGenerator:
  - name: helloworld-config
  - name: helloproperty
    files:
      - base_properties=properties

secretGenerator:
  - name: helloworld-secret